In [1]:
import numpy as np

## Method to create array

In [2]:
arr1 = np.array([1,2,3,4,5])
print("this is an one dimention array",arr1,"\n")
arr2 = np.array([[1,2,4,5],[6,7,8,9]])
print("this is an multidimention array \n",arr2)
#now we will create an array of different data type 
arr_of_friends = np.array(['mohan','rohan','sohan',12,3.7,True])
print("\n this is an different data type arrray \n",arr_of_friends)

this is an one dimention array [1 2 3 4 5] 

this is an multidimention array 
 [[1 2 4 5]
 [6 7 8 9]]

 this is an different data type arrray 
 ['mohan' 'rohan' 'sohan' '12' '3.7' 'True']


## dtype method

dtype parameter is use to specify the data type of sepcific elements in numpy array

In [3]:
#suppose we want to know the dtype of arra1
print("this data type of arr1 is",arr1.dtype)

#we call also set the data type in our code 
arr3 = np.array([188,655,890,654,234],dtype='int32')
print(arr3)

#suppose we have a float value and we use the dtype int32 
arr4 = np.array([188.7,655.9,890.6,654.4,234.2],dtype='int32')
print("yes we did not get the value in the form of float because we use the dtype as int32\n",arr4)

arr5 = np.array([188.7,655.9,890.6,654.4,234.2],dtype='float')
print("after using dtype as float \n",arr5)

this data type of arr1 is int32
[188 655 890 654 234]
yes we did not get the value in the form of float because we use the dtype as int32
 [188 655 890 654 234]
after using dtype as float 
 [188.7 655.9 890.6 654.4 234.2]


This is all about dtype method in numpy

 ## Shape and Reshape method in numpy

shape attribute is used to determine or specify the dimensions of a NumPy array . The shape attribute is a tuple representing the dimensions of the array, where each element of the tuple corresponds to the size of a specific dimension.

As by its name Reshape in use to reshape the given array .Reshaping is a common operation, especially when working with neural networks and machine learning.

let's see the practical use of it


In [4]:
arr6 = np.array([1,2,4,5,1])
print(arr6.shape) #this output represents the number of indexing present in arr6

arr7 = np.array([[1,2,4,5],[6,7,8,9]])
print(arr7.shape)#the output specifies that we have 2 rows and 4 columns 

(5,)
(2, 4)


In [5]:
#now we will see the reshape method which is used to reshape the given array for practical we are taking arr7 only here.
arr8 = arr7.reshape(4,2).copy() #.cope is used to create a copy of a NumPy array. and do not affect the real array if we perform any operation on it
print("this is a same array of arr7 but after we change the shape it converts 4rows and 2columns\n")
print(arr8)

#suppose we want to know the dimension of an array for that we use the ndim attribute 
print("this dimension of an arr8 is ",arr8.ndim)



this is a same array of arr7 but after we change the shape it converts 4rows and 2columns

[[1 2]
 [4 5]
 [6 7]
 [8 9]]
this dimension of an arr8 is  2


## Now we will see the blank array also called the zeors array

In [6]:
#for to create array of zero we use the numpy funstion np.zeros
#for creating 1 dimetion zeros array
arr9 = np.zeros(10)
print(arr9)
print("the dtype of arr9 is ",arr9.dtype)
print("\nthe shape of arr9 is ",arr9.shape)

#for multidimentional array 
arr10 = np.zeros((8,9))
print("\n",arr10)
print("\nthe shape of arr10 is",arr10.shape)
print("\nthe dtype od arr10 is",arr10.dtype)

#ones of array which we create using np.ones()
arr11 = np.ones(10)
print("\n",arr11)

#ones array in multidimention
arr12 = np.ones((7,8))
print("\n",arr12)

#empty array

arr13 = np.empty(8)#this will provide you the garbage value
print("\n",arr13)

#this is all about the blank array

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
the dtype of arr9 is  float64

the shape of arr9 is  (10,)

 [[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]

the shape of arr10 is (8, 9)

the dtype od arr10 is float64

 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]

 [6.23042070e-307 4.67296746e-307 1.69121096e-306 9.45741271e-308
 1.89146896e-307 7.56571288e-307 3.11525958e-307 1.24610723e-306]


## Arithmetic Operations is numpy

In [7]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,3]])
arr2 = np.array([[1,2,4,5,8],[6,7,8,9,8]])
print(arr1,"\n")
print(arr2,"\n")
print("the sum of arr1  is \n",arr1.sum(axis=0))
#by default it perform row + column operation if axis is 0
#but if we put axis is 1 then it will add all the element present in row and all the element present in coloumn 
print("\n the sum of arr2 in axis one ",arr2.sum(axis=1))
#the value of axis is always one or it should be zero(defalut)
print("\n it perform coloumn wise operation using both the array")
print("\n",np.multiply(arr1,arr2))
print("\n the division value of arr1 by 2\n",np.divide(arr1,2))
print("\n the division value of arr1 by arr2\n",np.divide(arr1,arr2))
print("\n the square root of arr1 is \n",np.sqrt(arr1))

#this are the just few example of numpy arithmetic operatios

[[1 2 3 4 5]
 [6 7 8 9 3]] 

[[1 2 4 5 8]
 [6 7 8 9 8]] 

the sum of arr1  is 
 [ 7  9 11 13  8]

 the sum of arr2 in axis one  [20 38]

 it perform coloumn wise operation using both the array

 [[ 1  4 12 20 40]
 [36 49 64 81 24]]

 the division value of arr1 by 2
 [[0.5 1.  1.5 2.  2.5]
 [3.  3.5 4.  4.5 1.5]]

 the division value of arr1 by arr2
 [[1.    1.    0.75  0.8   0.625]
 [1.    1.    1.    1.    0.375]]

 the square root of arr1 is 
 [[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         1.73205081]]


## Slicing

In [8]:
arr_slice = np.array([1,2,3,4,5,6,7,8])#one d array
arr2_slice = np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,6,7]])#2d array
print(arr_slice)
print(arr2_slice)
#first we find the length of arr_slice using length function
print("the length of arr_slice is :- ",len(arr_slice))
#always remember that slicing work by the help of indexing and indexing starts from zero so we can say that len - 1 = the in between value we want 
#syntax of Slicing
            #slicing for 1 dimention array[starting_indexing:ending_indexing+1]
print("the slicing of one dimention array",arr_slice[0:3])
#first we find the length of arr2_slice using length function
print("the length of arr2_slice is :- ",len(arr2_slice))
            #slicing for 2 dimention arr[number of row , starting_indexing:ending_indexing+1]
print("the slicing of two dimention array",arr2_slice[1,0:7]) 


[1 2 3 4 5 6 7 8]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 6 7]]
the length of arr_slice is :-  8
the slicing of one dimention array [1 2 3]
the length of arr2_slice is :-  2
the slicing of two dimention array [1 2 3 4 5 6 6]


## Sorting with numpy

Sorting is the process of arranging elements in a specific order, often ascending or descending, based on a defined criterion, such as numerical or lexicographical order

In [12]:
arr_sort = np.array([1,2,3,4,5,6,6,71,2,3,4,5,6,7,81,2,3,4,5,6,7,8])
print("the sorted array is :-")
print(np.sort(arr_sort,kind="mergesort"))
#by using kind attribute you can also specify the type of shorting algorithm to reduce the time complexity

the sorted array is :-
[ 1  2  2  2  3  3  3  4  4  4  5  5  5  6  6  6  6  7  7  8 71 81]
