In [1]:
import numpy as np

##method to create array

In [12]:
arr1 = np.array([1,2,3,4,5])
print("this is an one dimention array",arr1,"\n")
arr2 = np.array([[1,2,4,5],[6,7,8,9]])
print("this is an multidimention array \n",arr2)
#now we will create an array of different data type 
arr_of_friends = np.array(['mohan','rohan','sohan',12,3.7,True])
print("\n this is an different data type arrray \n",arr_of_friends)

this is an one dimention array [1 2 3 4 5] 

this is an multidimention array 
 [[1 2 4 5]
 [6 7 8 9]]

 this is an different data type arrray 
 ['mohan' 'rohan' 'sohan' '12' '3.7' 'True']


##dtype method

dtype parameter is use to specify the data type of sepcific elements in numpy array

In [25]:
#suppose we want to know the dtype of arra1
print("this data type of arr1 is",arr1.dtype)

#we call also set the data type in our code 
arr3 = np.array([188,655,890,654,234],dtype='int32')
print(arr3)

#suppose we have a float value and we use the dtype int32 
arr4 = np.array([188.7,655.9,890.6,654.4,234.2],dtype='int32')
print("yes we did not get the value in the form of float because we use the dtype as int32\n",arr4)

arr5 = np.array([188.7,655.9,890.6,654.4,234.2],dtype='float')
print("after using dtype as float \n",arr5)

this data type of arr1 is int32
[188 655 890 654 234]
yes we did not get the value in the form of float because we use the dtype as int32
 [188 655 890 654 234]
after using dtype as float 
 [188.7 655.9 890.6 654.4 234.2]
